# ***Description***

### Arc length constrained hermite spline with all the 12 cases given on 28 Oct 25

In [1]:
import utils
from scipy import optimize
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
import warnings
warnings.simplefilter('ignore')
mag=[]
prt_len=[]
ach_len=[]
err_len=[]

# Position 1

## Case 01

In [2]:
df=pd.read_csv('../data/2810/p1-case1.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 1 Case 1')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p1-case1.html')
fig.show()

Length of the Prototype Spline: 192.16046
Given target spline length: 192.16046
Length of the Hermite Spline: 51.44133
Achieved Length of the Hermite Spline: 192.16046

Computed Magnitude (X): 339.2314

## Case 02

In [3]:
df=pd.read_csv('../data/2810/p1-case2.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 1 Case 2')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p1-case2.html')
fig.show()

Length of the Prototype Spline: 183.67097
Given target spline length: 183.67097
Length of the Hermite Spline: 30.56224
Achieved Length of the Hermite Spline: 183.67097

Computed Magnitude (X): 428.4254

## Case 03

In [4]:
df=pd.read_csv('../data/2810/p1-case3.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 1 Case 3')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p1-case3.html')
fig.show()

Length of the Prototype Spline: 217.60053
Given target spline length: 217.60053
Length of the Hermite Spline: 44.46117
Achieved Length of the Hermite Spline: 217.60053

Computed Magnitude (X): 410.3608

# Position 2

## Case 01

In [5]:
df=pd.read_csv('../data/2810/p2-case1.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 2 Case 1')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p2-case1.html')
fig.show()

Length of the Prototype Spline: 192.18051
Given target spline length: 192.18051
Length of the Hermite Spline: 63.12531
Achieved Length of the Hermite Spline: 192.18051

Computed Magnitude (X): 326.3605

## Case 02

In [6]:
df=pd.read_csv('../data/2810/p2-case2.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 2 Case 2')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p2-case2.html')
fig.show()

Length of the Prototype Spline: 183.66672
Given target spline length: 183.66672
Length of the Hermite Spline: 33.05682
Achieved Length of the Hermite Spline: 183.66672

Computed Magnitude (X): 380.3374

## Case 03

In [7]:
df=pd.read_csv('../data/2810/p2-case3.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 2 Case 3')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p2-case3.html')
fig.show()

Length of the Prototype Spline: 217.58790
Given target spline length: 217.58790
Length of the Hermite Spline: 54.14167
Achieved Length of the Hermite Spline: 217.58790

Computed Magnitude (X): 430.6150

# Position 3

## Case 01

In [8]:
df=pd.read_csv('../data/2810/p3-case1.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 3 Case 1')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(autosize=True)
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
pio.write_html(fig,'../ppt/1411-arc-len-herm/p3-case1.html')
fig.show()

Length of the Prototype Spline: 192.18447
Given target spline length: 192.18447
Length of the Hermite Spline: 72.11077
Achieved Length of the Hermite Spline: 192.18447

Computed Magnitude (X): 329.6626

## Case 02

In [9]:
df=pd.read_csv('../data/2810/p3-case2.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 3 Case 2')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(autosize=True)
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
pio.write_html(fig,'../ppt/1411-arc-len-herm/p3-case2.html')
fig.show()

Length of the Prototype Spline: 183.68014
Given target spline length: 183.68014
Length of the Hermite Spline: 39.03914
Achieved Length of the Hermite Spline: 183.68014

Computed Magnitude (X): 346.2583

## Case 03

In [10]:
df=pd.read_csv('../data/2810/p3-case3.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 3 Case 3')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(autosize=True)
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
pio.write_html(fig,'../ppt/1411-arc-len-herm/p3-case3.html')
fig.show()

Length of the Prototype Spline: 217.56689
Given target spline length: 217.56689
Length of the Hermite Spline: 63.33947
Achieved Length of the Hermite Spline: 217.56689

Computed Magnitude (X): 444.3351

# Position 4

## Case 01

In [11]:
df=pd.read_csv('../data/2810/p4-case1.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 4 Case 1')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p4-case1.html')
fig.show()

Length of the Prototype Spline: 192.24013
Given target spline length: 192.24013
Length of the Hermite Spline: 77.23709
Achieved Length of the Hermite Spline: 192.24013

Computed Magnitude (X): 349.2389

## Case 02

In [12]:
df=pd.read_csv('../data/2810/p4-case2.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 4 Case 2')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p4-case2.html')
fig.show()

Length of the Prototype Spline: 184.71879
Given target spline length: 184.71879
Length of the Hermite Spline: 45.51395
Achieved Length of the Hermite Spline: 184.71879

Computed Magnitude (X): 331.3326

## Case 03

In [13]:
df=pd.read_csv('../data/2810/p4-case3.csv')
prt=df.iloc[10:,2:].reset_index(drop=True)

p0=df.iloc[5,2:].values.astype(float)    # Point0
p1=df.iloc[6,2:].values.astype(float)    # Point1
u0=df.iloc[8,2:].values.astype(float)    # Unit Vector @ Point0
u1=df.iloc[9,2:].values.astype(float)    # Unit Vector @ Point1
m0=df.iloc[2,1]                          # Magnitude for Vector1
m1=df.iloc[3,1]                          # Magnitude for Vector2
u0_init=u0*m0
u1_init=u1*m1
spl=utils.hermite(p0, p1, u0_init, u1_init,num_points=51)

tgt=utils.length(prt.values)             # Target spline length

obj_fn=lambda x: utils.length(utils.hermite(p0,p1,x*u0,x*u1)) - tgt
sol=optimize.root_scalar(obj_fn, bracket=[0, tgt*3], method='brentq')
solx=sol.root
u0_final=solx*u0
u1_final=solx*u1
spl=utils.hermite(p0,p1,u0_init,u1_init,num_points=100)
spl_tgt=utils.hermite(p0,p1,u0_final,u1_final,num_points=100)

print(f'Length of the Prototype Spline: {utils.length(prt.values):.5f}')
print(f'Given target spline length: {tgt:.5f}')
print(f'Length of the Hermite Spline: {utils.length(spl.astype(float)):.5f}')
print(f'Achieved Length of the Hermite Spline: {utils.length(spl_tgt.astype(float)):.5f}')
print(f'\nComputed Magnitude (X): {solx:.4f}')

a=prt.iloc[50]
b=pd.DataFrame(spl_tgt,columns=prt.columns).iloc[50]
mag.append(np.round(solx,3))
prt_len.append(utils.length(prt.values).round(3))
ach_len.append(utils.length(spl_tgt.astype(float)).round(3))
err_len.append(utils.length(pd.DataFrame([a,b]).values).round(3))
fig=utils.plotter_v2(spl,p0,p1,u0_init,u1_init,spl1=spl_tgt,spl2=prt.values,x_label='Unoptimized Hermite Spline',
                     spl1_label='Optimized hermite spline',spl2_label='Prototype',cne=6,intr='d',height=550,width=900,title='Position 4 Case 3')
fig.add_trace(go.Scatter3d(x=[a[0],b[0]],y=[a[1],b[1]],z=[a[2],b[2]],mode='lines',name='Midpoint Deviation'
                           ,line=dict(color='red',width=6,dash='longdash'),text='Length '+str(utils.length(pd.DataFrame([a,b]).values).round(2)))) 
fig.update_layout(legend=dict(x=0.75,y=1,xanchor="left",yanchor="top"))
fig.update_layout(autosize=True)
pio.write_html(fig,'../ppt/1411-arc-len-herm/p4-case3.html')
fig.show()

Length of the Prototype Spline: 217.55841
Given target spline length: 217.55841
Length of the Hermite Spline: 69.80785
Achieved Length of the Hermite Spline: 217.55841

Computed Magnitude (X): 458.4657

## Error Matrix

In [14]:
pos=[]
cas=[]
for i in range(1,5):
    for j in range(1,4):
        pos.append(int(i))
        cas.append(int(j))
cor=pd.DataFrame([pos,cas,mag,prt_len,ach_len,err_len]).T
cor.columns=['Position','Case','Computed Magnitude','Length - Prototype','Length - Optimized Hermite','Error - Midpoint Deviation']
cor['Error - Length']=cor.iloc[:,4]-cor.iloc[:,3]
cor['Position']=cor['Position'].astype(int)
cor['Case']=cor['Case'].astype(int)
cor

,Position,Case,Computed Magnitude,Length - Prototype,Length - Optimized Hermite,Error - Midpoint Deviation,Error - Length
0,1,1,339.231,192.160,192.160,27.232,0.0
1,1,2,428.425,183.671,183.671,29.464,0.0
2,1,3,410.361,217.601,217.601,24.393,0.0
3,2,1,326.361,192.181,192.181,31.582,0.0
4,2,2,380.337,183.667,183.667,22.649,0.0
5,2,3,430.615,217.588,217.588,31.889,0.0
6,3,1,329.663,192.184,192.184,37.735,0.0
7,3,2,346.258,183.680,183.680,21.762,0.0
8,3,3,444.335,217.567,217.567,44.350,0.0
9,4,1,349.239,192.240,192.240,40.860,0.0
10,4,2,331.333,184.719,184.719,24.860,0.0
11,4,3,458.466,217.558,217.558,49.024,0.0

In [15]:
cor.corr().round(3)

,Position,Case,Computed Magnitude,Length - Prototype,Length - Optimized Hermite,Error - Midpoint Deviation,Error - Length
Position,1.000,0.000,-0.104,0.008,0.008,0.515,NaN
Case,0.000,1.000,0.849,0.724,0.724,0.146,NaN
Computed Magnitude,-0.104,0.849,1.000,0.707,0.707,0.428,NaN
Length - Prototype,0.008,0.724,0.707,1.000,1.000,0.530,NaN
Length - Optimized Hermite,0.008,0.724,0.707,1.000,1.000,0.530,NaN
Error - Midpoint Deviation,0.515,0.146,0.428,0.530,0.530,1.000,NaN
Error - Length,NaN,NaN,NaN,NaN,NaN,NaN,NaN