In [1]:
import pandas as pd
import utils

In [2]:
df=[]
si=[]
pos=[]
cas=[]
ln=[]
for i in range(1,5):
    for j in range(1,4):
        df.append(pd.read_csv('../data/2810/p'+str(i)+'-case'+str(j)+'.csv'))
        si.append(pd.read_csv('data/p'+str(i)+'-case'+str(j)+'.csv'))
        ln.append(utils.length(pd.DataFrame([df[len(pos)].iloc[59,2:],si[len(pos)].iloc[50]]).values))
        pos.append(i)
        cas.append(j)
cor=pd.DataFrame([pos,cas,ln]).T
cor.columns=['Position','Case','Error']
cor

    Position  Case      Error
0        1.0   1.0   9.967515
1        1.0   2.0  49.672017
2        1.0   3.0  37.664630
3        2.0   1.0  13.449645
4        2.0   2.0  35.591078
5        2.0   3.0  30.512298
6        3.0   1.0  15.736890
7        3.0   2.0  30.244046
8        3.0   3.0  22.617270
9        4.0   1.0  14.257154
10       4.0   2.0  17.021717
11       4.0   3.0  24.885970

In [3]:
cor.corr().round(3)

          Position   Case  Error
Position     1.000  0.000 -0.438
Case         0.000  1.000  0.556
Error       -0.438  0.556  1.000