In [1]:
import pandas as pd
import utils

In [2]:
df=[]
si=[]
he=[]
pos=[]
cas=[]
er_sim=[]
er_her=[]
for i in range(1,5):
    for j in range(1,4):
        df.append(pd.read_csv('../data/2810/p'+str(i)+'-case'+str(j)+'.csv'))
        si.append(pd.read_csv('data/p'+str(i)+'-case'+str(j)+'.csv'))
        he.append(pd.read_csv('../data/2810/opt/p'+str(i)+'-case'+str(j)+'-opt.csv'))
        er_sim.append(utils.length(pd.DataFrame([df[len(pos)].iloc[59,2:],si[len(pos)].iloc[50]]).values))
        er_her.append(utils.length(pd.DataFrame([df[len(pos)].iloc[59,2:],he[len(pos)].iloc[50]]).values))
        pos.append(int(i))
        cas.append(int(j))
cor=pd.DataFrame([pos,cas,er_sim,er_her]).T
cor.columns=['Position','Case','Error - Simulation','Error - Hermite']
cor

    Position  Case  Error - Simulation  Error - Hermite
0        1.0   1.0           10.421226        22.694771
1        1.0   2.0            9.117420        29.268214
2        1.0   3.0           15.224732        22.225684
3        2.0   1.0            7.100324        29.336589
4        2.0   2.0           16.984183        21.194052
5        2.0   3.0           23.643960        20.110613
6        3.0   1.0            9.392825        32.329889
7        3.0   2.0           19.040114        19.542604
8        3.0   3.0           21.088619        26.514787
9        4.0   1.0            8.214040        20.924576
10       4.0   2.0           20.690918        19.014673
11       4.0   3.0           22.088941        28.402183

In [3]:
cor.corr().round(3)

                    Position   Case  Error - Simulation  Error - Hermite
Position               1.000  0.000               0.322           -0.083
Case                   0.000  1.000               0.820           -0.186
Error - Simulation     0.322  0.820               1.000           -0.432
Error - Hermite       -0.083 -0.186              -0.432            1.000